### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by theolau** [theolau/group3-s-project-1#16]
as of https://github.com/theolau/group3-s-project-1/pull/15, this is what still needs to be completed

todo list:
- [ ] fix ui (miranda's working on it)
       - flexbox widths, framework, overall ui look, portfolio colors, etc
- [ ] optional: add button to clear memory + client side storage
       - think of it as a reset button
- [ ] add error popup / display
       - there's a lot of stuff we just output to console (insufficient cash to purchase, etc), would be nice to display this somewhere
- [ ] market data api (waiting on andrew to push code)
- [ ] use market data api to calculate current price of a coin in currentPrice()
       - this needs to cache data for probably 30s+ to minimize api calls
       - use setInterval() and pageRefresh() to grab new data every x (currently 15) seconds
- [ ] use market data api to create a graph (just hardcode duration as 7 days or whatever is easiest)
       - add to the on select function
- [ ] use market data api to calculate today's gain loss
       - might have to start saving a first transaction date in order to be able to do this
- [ ] fix createCoinRow() and deleteRow() to alternate colors on row generation & fix colors on row deletion
- [ ] clean up unnecessary comments & commented out code
       - this can wait until just prior to release
